import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className="container mx-auto p-5">
          <div className="flex justify-between items-center">
            <span className="text-lg">Logo</span>
            <ul className="flex space-x-5">
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/about">About Us</Link>
              </li>
              <li>
                <Link href="/contact">Contact Us</Link>
              </li>
            </ul>
          </div>
        </header>
        {children}
        <footer className="container mx-auto p-5 text-center">
            Footer
        </footer>
      </body>
    </html>
  );
}
